# PV
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /meubanco/

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
# database deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: srjaizer/proj-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql

      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local

---
# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: srjaizer/proj-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

